eye_colours = [
    "Dead",
    "Grey",
    "Sulfur",
    "Green",
    "Copper",
    "Hazel",
    "Blue",
    "RedDevil",
    "Red",
    "Iron",
    "Brown",
    "BrownDark",
]

hair_brow_colours = [
    "White",
    "Platinum",
    "Grey",
    "Blonde",
    "DirtyBlonde",
    "Amber",
    "Copper",
    "Ruby",
    "SaltAndBrown",
    "Brown",
    "SaltAndPepper",
    "BlackBrown",
    "Auburn",
    "Black",
    "Jet",
    "TealBlonde",
    "Yellow",
    "Violet",
    "Flame",
    "Blue",
    "Fuchsia",
    "AquaPurple",
    "Teal",
]

brow_styles = [
    "Sparse",
    "Standard",
    "Fluffy",
    "Apart",
    "Stern",
    "ThinArched",
    "ThickArched",
    "ThinFlat",
    "Sliced",
    "Simple",
    "Connected",
]

hair_styles = [
    "Faded_Afro",
    "Messy_Updo",
    "Receding_Wizard",
    "Mullet",
    "Short_Ponytail_HairMesh",
    "Finger_Waves",
    "Cornrows_HairMesh",
    "Straight_Bob",
    "Whitney_Curls",
    "Cropped_Bang",
    "Bob",
    "Hairspray_Bob",
    "OldGuy_Business",
    "Viking_Braids",
    "Dreadlocks_HairMesh",
    "Even_Buzz_Back",
    "Ponytail_HairMesh",
    "Hollywood_curls",
    "Messy_Business",
    "Unkempt",
    "Top_Bun",
    "Cropped",
    "Colly_Mohawk",
    "Natural_Fade",
    "Short_Afro",
    "Shaggy",
    "Flat_Top",
    "Messy_Bob",
    "Spiked",
    "Business",
    "Undercut",
    "Mullet_Mohawk",
    "Buzz_Mohawk",
    "None",
    "High_and_Tight",
    "Wavy_Business",
    "CyberFade",
    "Tousled_Bob",
    "Choppy_Bob",
    "Short_Loc",
]

features = [
    "Neck",
    "Cheeks",
    "Jaw",
    "Chin",
    "Ears",
    "Eyes",
    "Forehead",
    "Mouth",
    "Nose",
]

variations = [
    "as_md1",
    "af_md1",
    "as_ol1",
    "af_yo1",
    "eu_md2",
    "af_ol1",
    "as_yo1",
    "eu_ol1",
    "eu_yo1",
]

feature_regions = [17, 1, 3, 19, 11, 5, 13, 15, 9]

additional_regions = {
    23: list(range(24, 28)),
    29: list(range(30, 32)),
    33: list(range(34, 37)),
    37: list(range(38, 41)),
    41: list(range(42, 46)),
    46: list(range(47, 50)),
    50: list(range(51, 56)) + [75] + list(range(77, 80)),
    56: list(range(57, 60)),
    60: list(range(61, 64)),
    64: [65, 67, 69, 70],
    71: list(range(72, 74)),
}

skin_tones = list(range(1, 10))